# Numpy


## Installation

In [2]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


## Creating 1-D array

In [3]:
import numpy as np

In [4]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


## Creating 2-D array

In [5]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


## Creating 3-D array

In [6]:
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Pandas

## Installing Pandas

In [7]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------- ----------------------------- 2.9/11.0 MB 23.8 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/11.0 MB 19.8 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 20.3 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 19.0 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [8]:
import pandas as pd

In [10]:
s=pd.Series([1,3,5,7,9], name="My number series")
print(f"Pandas Series:\n{s}")
print(f"type of s: {type(s)}")


Pandas Series:
0    1
1    3
2    5
3    7
4    9
Name: My number series, dtype: int64
type of s: <class 'pandas.core.series.Series'>


## Create a pandas Dataframe from a dictionary

In [11]:
data={'Name': ['Alice', 'Bob', 'Charlie', 'David'],
      'Age': [24, 27, 22, 32],
      'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
      'Score': [85.5, 90.0, 78.5, 88.0]}
df=pd.DataFrame(data)
print(f"\nPandas DataFrame:\n{df}")


Pandas DataFrame:
      Name  Age         City  Score
0    Alice   24     New York   85.5
1      Bob   27  Los Angeles   90.0
2  Charlie   22      Chicago   78.5
3    David   32      Houston   88.0
